In [14]:
# Regression Example with  Keras

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]] , columns=['cgpa', 'profile_score', 'lpa'])


In [3]:
df

cgpa  profile_score  lpa
0     8              8    4
1     7              9    5
2     6             10    6
3     5             12    7

In [4]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

2025-05-18 08:01:54.535448: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2025-05-18 08:01:54.846782: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2025-05-18 08:01:54.988531: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2025-05-18 08:01:55.270620: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2025-05-18 08:01:55.338998: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2025-05-18 08:01:55.737000: I tensorflow/core/platform/cpu_feature_gu

In [5]:
model = Sequential()

model.add(Dense(2, activation='linear',input_dim=2))
model.add(Dense(1, activation='linear'))

/home/sarthakredasani/.local/lib/python3.11/site-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [6]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 2)              │             6 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [7]:
model.get_weights()

[array([[-0.9132781 ,  0.48034406],
        [-0.3166104 , -1.1621587 ]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[-0.01258743],
        [-1.0788729 ]], dtype=float32),
 array([0.], dtype=float32)]

In [8]:
new_weights = [np.array([[0.1, 0.1], [0.1, 0.1]], dtype=np.float32),
                np.array([0., 0.1], dtype=np.float32),
                  np.array([[0.1], [0.1]], dtype=np.float32),
                    np.array([0.1], dtype=np.float32)]

In [9]:
model.set_weights(new_weights)

In [10]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0. , 0.1], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.1], dtype=float32)]

In [11]:
optimizer = keras.optimizers.Adam(learning_rate=0.01)
model.compile(optimizer=optimizer, loss='mean_squared_error')


In [12]:
model.fit(df.iloc[:,0:-1].values, df['lpa'].values, epochs=75, verbose=1, batch_size=1)


Epoch 1/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 21.7999
Epoch 2/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 20.1106 
Epoch 3/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 20.8039 
Epoch 4/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 11.8715
Epoch 5/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 6.8841  
Epoch 6/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 5.2790 
Epoch 7/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 2.3654 
Epoch 8/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.9897 
Epoch 9/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.2770 
Epoch 10/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 1.2156  
Epoch 11/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 2.5396 
Epoch 12/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 2.1052 
Epoch 13/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 1.7712
Epoch 14/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.9319 
Epoch 15/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.6533 
Epoch 16/75
4/4 ━━━━

In [13]:
model.get_weights()


[array([[0.031173  , 0.03161771],
        [0.5660854 , 0.56592435]], dtype=float32),
 array([0.2267178 , 0.32685608], dtype=float32),
 array([[0.43594596],
        [0.43390375]], dtype=float32),
 array([0.33760658], dtype=float32)]